### ISSUE TITLE
The costume name is slightly incorrect.

### ISSUE THREAD

**Issue by darkeroticism** [ShinyColorsDB/ShinyColorsDB-ApiServer#1]
Hi. I thought it would be better to open an issue here regarding incorrect data, so I came here to report it.

The costume name is "ユナイトバースプライネタ**り**", but "ユナイトバースプライネタ**リ**" is correct. 
Only the last character is in hiragana instead of katakana. I think it would be better to fix it because it gives the impression that ``foreigners are creating this system.''
This is because it is known among Japanese people as a character that Japanese learners often make mistakes with.

**Comment by alex94539** [comment]
fixed :) thanks for pointing out
